import { PromptTemplate } from '../shared/types/prompt-templates';

export const BUILT_IN_ACTIONS: PromptTemplate[] = [
  {
    id: 'explain-code',
    type: 'built-in',
    name: 'Explain Code',
    description: 'Get a detailed explanation of selected code',
    prompt: 'Please explain this code:\n\n{selection}',
    keywords: ['explain', 'describe', 'what does', 'code'],
    icon: 'MessageCircle',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'improve-code',
    type: 'built-in',
    name: 'Improve Code',
    description: 'Suggest improvements for code quality and performance',
    prompt: 'Please review this code and suggest improvements for quality, performance, and best practices:\n\n{selection}',
    keywords: ['improve', 'optimize', 'refactor', 'better'],
    icon: 'Sparkles',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'fix-bugs',
    type: 'built-in',
    name: 'Fix Bugs',
    description: 'Identify and fix potential bugs in code',
    prompt: 'Please identify any bugs or issues in this code and suggest fixes:\n\n{selection}',
    keywords: ['fix', 'bug', 'error', 'debug'],
    icon: 'Bug',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'add-comments',
    type: 'built-in',
    name: 'Add Comments',
    description: 'Add documentation comments to code',
    prompt: 'Please add comprehensive comments and documentation to this code:\n\n{selection}',
    keywords: ['comment', 'document', 'docs', 'documentation'],
    icon: 'FileText',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'write-tests',
    type: 'built-in',
    name: 'Write Tests',
    description: 'Generate unit tests for code',
    prompt: 'Please write comprehensive unit tests for this code:\n\n{selection}',
    keywords: ['test', 'unit test', 'testing', 'jest', 'mocha'],
    icon: 'TestTube',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'convert-typescript',
    type: 'built-in',
    name: 'Convert to TypeScript',
    description: 'Convert JavaScript code to TypeScript',
    prompt: 'Please convert this JavaScript code to TypeScript with proper types:\n\n{selection}',
    keywords: ['typescript', 'ts', 'convert', 'types'],
    icon: 'Code',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'security-review',
    type: 'built-in',
    name: 'Security Review',
    description: 'Check code for security vulnerabilities',
    prompt: 'Please review this code for security vulnerabilities and suggest fixes:\n\n{selection}',
    keywords: ['security', 'vulnerability', 'secure', 'safety'],
    icon: 'Shield',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'generate-readme',
    type: 'built-in',
    name: 'Generate README',
    description: 'Create a README for the current project',
    prompt: 'Please create a comprehensive README.md for the project in {current_dir}. Include sections for installation, usage, and features.',
    keywords: ['readme', 'documentation', 'docs', 'markdown'],
    icon: 'Book',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'commit-message',
    type: 'built-in',
    name: 'Generate Commit Message',
    description: 'Create a descriptive git commit message',
    prompt: 'Please analyze the current changes in {current_dir} and suggest a descriptive git commit message following conventional commits format.',
    keywords: ['commit', 'git', 'message', 'conventional'],
    icon: 'GitCommit',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'analyze-clipboard',
    type: 'built-in',
    name: 'Analyze Clipboard',
    description: 'Analyze content from clipboard',
    prompt: 'Please analyze this content:\n\n{clipboard}',
    keywords: ['clipboard', 'analyze', 'paste', 'review'],
    icon: 'Clipboard',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'summarize-selection',
    type: 'built-in',
    name: 'Summarize',
    description: 'Create a concise summary of selected text',
    prompt: 'Please provide a concise summary of:\n\n{selection}',
    keywords: ['summarize', 'summary', 'tldr', 'brief'],
    icon: 'AlignLeft',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'quick-question',
    type: 'built-in',
    name: 'Quick Question',
    description: 'Ask a quick question about the codebase',
    prompt: 'Quick question about {current_dir}: ',
    keywords: ['question', 'ask', 'help', 'how'],
    icon: 'HelpCircle',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];
